[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "npm run build",
  "mkdir -p server/public",
  "cp -r dist/public/* server/public/ || echo 'Static files copy failed, continuing...'"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"